export const ROLES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  OPERADOR: 'OPERADOR',
  DOCENTE: 'DOCENTE',
  JEFE_ESCUELA: 'JEFE_ESCUELA',
  AUDITOR: 'AUDITOR',
} as const;

export const MODALIDADES = ['NOMBRADO', 'CONTRATADO'] as const;
export const CATEGORIAS = ['PRINCIPAL', 'ASOCIADO', 'AUXILIAR', 'JEFE_PRACTICA'] as const;